# Tomcat
server:
    tomcat:
        max-threads: 10
        min-spare-threads: 10
    port: 8080

# mysql
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://172.16.1.133:3306/docker-test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
        username: root
        password: 123456
#        driverClassName: org.h2.Driver
#        url: jdbc:h2:mem:dbtest
#        username: sa
#        password:

    redis:
      cluster:
        nodes: 172.16.1.132:7001,172.16.1.132:7002,172.16.1.132:7003,172.16.1.132:7004,172.16.1.132:7005,172.16.1.132:7006



