#FROM docker.elastic.co/elasticsearch/elasticsearch:6.4.0
#RUN ulimit -m unlimited
#ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
#CMD ["eswrapper"]

#FROM docker.elastic.co/apm/apm-server:6.4.0

FROM docker.elastic.co/elasticsearch/elasticsearch-platinum:6.4.0