version: '3.6'


#docker stack deploy -c /root/elk/docker-compose.yml elk

volumes:
  esdata:
    driver: local
#  beatdata:
#    driver: local
networks:
  esnet:
    driver: overlay
#    attachable: true
configs:
  logstash_conf:
    file: ./logstash/logstash.conf
  kibana_config:
    file: ./kibana/kibana.yml
  apm_server_config:
    file: ./apm_server/apm-server.yml
  es_proxy_config:
    file: ./es_proxy/nginx.conf
#  filebeat_config:
#    file: ./filebeat/filebeat.yml
services:
  elasticsearch:
    image: hub.c.163.com/muxiyue/elasticsearch:6.4.0-crack
    #hostname: elasticsearch
    environment:
      - "cluster.name=es-cluster"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "network.host=0.0.0.0"
      - "discovery.zen.minimum_master_nodes=2"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
      - "ELASTIC_PASSWORD=elastic"
      - "xpack.security.audit.enabled=true"
#      https://www.elastic.co/guide/en/elasticsearch/reference/6.4/configuring-tls.html#node-certificates
#      https://www.elastic.co/guide/en/elasticsearch/reference/6.4/configuring-tls-docker.html
#  license.json 上传之前，改为false，上传之后再改回成true，具体见x-pack下面的破解说明。
      - "xpack.security.enabled=true"
#      - xpack.security.http.ssl.enabled=true
      - "xpack.security.transport.ssl.enabled=true"
      - "xpack.security.transport.ssl.verification_mode=certificate"
      - "xpack.ssl.certificate_authorities=certs/ca/ca.crt"
      - "xpack.ssl.certificate=certs/elastic/elastic.crt"
      - "xpack.ssl.key=certs/elastic/elastic.key"

    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - esnet
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - /etc/localtime:/etc/localtime:ro
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.elasticsearch == elasticsearch
      restart_policy:
        condition: on-failure
      endpoint_mode: dnsrr
#    ports:
#      - "9200:9200"
#      - "9300:9300"

  logstash:
    image: hub.c.163.com/muxiyue/logstash:6.4.0
    hostname: logstash
    environment:
      - "xpack.monitoring.elasticsearch.url=http://elasticsearch:9200"
      - "xpack.monitoring.enabled=true"
      - "xpack.monitoring.elasticsearch.username=elastic"
      - "xpack.monitoring.elasticsearch.password=elastic"
      - "LS_JAVA_OPTS=-Xmx2g"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2048M
      placement:
        constraints:
          - node.labels.logstash == logstash
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - 5044:5044
    networks:
      - esnet
    configs:
      - source: logstash_conf
        target: /usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch

  kibana:
    image: hub.c.163.com/muxiyue/kibana:6.4.0-chinese
    hostname: kibana
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
    ports:
      - "5601:5601"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    deploy:
      placement:
        constraints:
           - node.role == manager
           - node.labels.kibana == kibana
      restart_policy:
        condition: on-failure
    depends_on:
      - elasticsearch
    networks:
      - esnet
    configs:
      - source: kibana_config
        target: /usr/share/kibana/config/kibana.yml

  es_proxy:
    image: hub.c.163.com/library/nginx:1.13.0
    ports:
      - "9200:80"
    depends_on:
      - elasticsearch
    networks:
      - esnet
    volumes:
      - /etc/localtime:/etc/localtime:ro
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 1024M
      update_config:
        parallelism: 1
        delay: 5s
      placement:
        constraints:
          - node.role != manager
      restart_policy:
        condition: on-failure
    configs:
      - source: es_proxy_config
        target: /etc/nginx/nginx.conf

  apm-server:
    image: hub.c.163.com/muxiyue/apm-server:6.4.0
    hostname: apm-server
    ports:
      - "8200:8200"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    deploy:
      placement:
        constraints:
          - node.labels.apmserver == apmserver
      restart_policy:
        condition: on-failure
    depends_on:
      - elasticsearch
    networks:
      - esnet
    configs:
      - source: apm_server_config
        target: /usr/share/apm-server/apm-server.yml

#swarm不支持
#  logpilot:
#      image: registry.cn-hangzhou.aliyuncs.com/acs-sample/log-pilot:latest
#      hostname: logpilot
#      environment:
#        - "PILOT_TYPE=filebeat"
#        - "LOGGING_OUTPUT=logstash"
#        - "LOGSTASH_HOST=logstash"
#        - "LOGSTASH_PORT=5044"
#        - "NODE_NAME=${NODE_NAME}"
#      networks:
#        - esnet
#      depends_on:
#        - logstash
#      privileged: true
#      volumes:
#        - /etc/localtime:/etc/localtime:ro
#        - beatdata:/var/lib/filebeat
#        - /var/run/docker.sock:/var/run/docker.sock
#        - /:/host:ro
#      deploy:
#        mode: global
#        restart_policy:
#          condition: on-failure

# 暂时不用，使用log-pilot


#  mount 172.16.1.191:/logs /logs

#  时区修改
#  mv /etc/localtime /etc/localtime.bak
#  ln -s /usr/share/zoneinfo/Asia/Shanghai  /etc/localtime
#  date
#
#
#  docker ps -a |grep log-pilot| awk '{print $1}'|xargs docker rm -f
#
#  docker login 172.16.1.146 -p 1qaz\!QAZ -u admin
#  docker run -itd \
#  --name log-pilot \
#  -v /var/run/docker.sock:/var/run/docker.sock \
#  -v /:/host:ro \
#  -v /etc/localtime:/etc/localtime:ro \
#  -e PILOT_TYPE=filebeat \
#  -e LOGGING_OUTPUT=logstash  \
#  -e LOGSTASH_HOST=localhost \
#  -e LOGSTASH_PORT=5044 \
#  --privileged \
#  --restart=always  \
#  --net=host \
#  registry.cn-hangzhou.aliyuncs.com/acs-sample/log-pilot:latest
#
#
#  172.16.1.146/perferct/log-pilot:latest-multiline

#  hub.c.163.com/muxiyue/log-pilot:latest-multiline

#  registry.cn-hangzhou.aliyuncs.com/acs-sample/log-pilot:latest


#  filebeat:
#      image: hub.c.163.com/muxiyue/filebeat:6.4.0
#      hostname: filebeat
#      networks:
#        - esnet
#      depends_on:
#        - logstash
#        - elasticsearch
#      privileged: true
#      volumes:
#        - /home/elk/filebeat/logs:/usr/share/filebeat/logs
#        - /home/logs:/home/logs:ro
#        - /etc/localtime:/etc/localtime:ro
#        - /home/elk/filebeat/registry:/usr/share/filebeat/data/registry
#      configs:
#        - source: filebeat_config
#          target: /usr/share/filebeat/filebeat.yml
#      deploy:
#        mode: global
#        restart_policy:
#          condition: on-failure